stages:
  - deploy

production:
  only:
    - tags
  tags:
    - autoscale-ci
  image: golang:1.14.1-buster
  stage: deploy
  before_script:
    # Create a symbolic link under $GOPATH, this is needed for local build
    # i.e. /go/src/gitlab.com/ykyuen/gitlab-ci-go-build
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
    # Install required dependencies for building the binary
    - go get -v -u github.com/golang/dep/...
    # Install serverless utility
    - curl -o- -L https://slss.io/install | bash
    - export PATH="$HOME/.serverless/bin:$PATH"
  script:
    - make
    - serverless deploy --stage production --verbose --region eu-north-1
    - serverless deploy --stage production --verbose --region ap-south-1
    - serverless deploy --stage production --verbose --region eu-west-3
    - serverless deploy --stage production --verbose --region eu-west-2
    - serverless deploy --stage production --verbose --region eu-west-1
    - serverless deploy --stage production --verbose --region ap-northeast-2
    - serverless deploy --stage production --verbose --region ap-northeast-1
    - serverless deploy --stage production --verbose --region sa-east-1
    - serverless deploy --stage production --verbose --region ca-central-1
    - serverless deploy --stage production --verbose --region ap-southeast-1
    - serverless deploy --stage production --verbose --region ap-southeast-2
    - serverless deploy --stage production --verbose --region eu-central-1
    - serverless deploy --stage production --verbose --region us-east-1
    - serverless deploy --stage production --verbose --region us-east-2
    - serverless deploy --stage production --verbose --region us-west-1
    - serverless deploy --stage production --verbose --region us-west-2
