stages:
  - deploy

production:
  only:
    - tags
  tags:
    - autoscale-ci
  image: golang:1.14-buster
  stage: deploy
  before_script:
    # Create a symbolic link under $GOPATH, this is needed for local build
    # i.e. /go/src/gitlab.com/ykyuen/gitlab-ci-go-build
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
    # Install required dependencies for building the binary
    - go get -v -u github.com/golang/dep/...
  script:
    - make
    - serverless deploy --stage production --verbose --region eu-west-1
    - serverless deploy --stage production --verbose --region us-east-1
